require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe AgentsController do

  def mock_agent(stubs={})
    @mock_agent ||= mock_model(Agent, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all agents as @agents" do
      Agent.stub(:all) { [mock_agent] }
      get :index
      assigns(:agents).should eq([mock_agent])
    end
  end

  describe "GET show" do
    it "assigns the requested agent as @agent" do
      Agent.stub(:find).with("37") { mock_agent }
      get :show, :id => "37"
      assigns(:agent).should be(mock_agent)
    end
  end

  describe "GET new" do
    it "assigns a new agent as @agent" do
      Agent.stub(:new) { mock_agent }
      get :new
      assigns(:agent).should be(mock_agent)
    end
  end

  describe "GET edit" do
    it "assigns the requested agent as @agent" do
      Agent.stub(:find).with("37") { mock_agent }
      get :edit, :id => "37"
      assigns(:agent).should be(mock_agent)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created agent as @agent" do
        Agent.stub(:new).with({'these' => 'params'}) { mock_agent(:save => true) }
        post :create, :agent => {'these' => 'params'}
        assigns(:agent).should be(mock_agent)
      end

      it "redirects to the created agent" do
        Agent.stub(:new) { mock_agent(:save => true) }
        post :create, :agent => {}
        response.should redirect_to(agent_url(mock_agent))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved agent as @agent" do
        Agent.stub(:new).with({'these' => 'params'}) { mock_agent(:save => false) }
        post :create, :agent => {'these' => 'params'}
        assigns(:agent).should be(mock_agent)
      end

      it "re-renders the 'new' template" do
        Agent.stub(:new) { mock_agent(:save => false) }
        post :create, :agent => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested agent" do
        Agent.stub(:find).with("37") { mock_agent }
        mock_agent.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :agent => {'these' => 'params'}
      end

      it "assigns the requested agent as @agent" do
        Agent.stub(:find) { mock_agent(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:agent).should be(mock_agent)
      end

      it "redirects to the agent" do
        Agent.stub(:find) { mock_agent(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(agent_url(mock_agent))
      end
    end

    describe "with invalid params" do
      it "assigns the agent as @agent" do
        Agent.stub(:find) { mock_agent(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:agent).should be(mock_agent)
      end

      it "re-renders the 'edit' template" do
        Agent.stub(:find) { mock_agent(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested agent" do
      Agent.stub(:find).with("37") { mock_agent }
      mock_agent.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the agents list" do
      Agent.stub(:find) { mock_agent }
      delete :destroy, :id => "1"
      response.should redirect_to(agents_url)
    end
  end

end
