require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe JobseekersController do

  def mock_jobseeker(stubs={})
    @mock_jobseeker ||= mock_model(Jobseeker, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all jobseekers as @jobseekers" do
      Jobseeker.stub(:all) { [mock_jobseeker] }
      get :index
      assigns(:jobseekers).should eq([mock_jobseeker])
    end
  end

  describe "GET show" do
    it "assigns the requested jobseeker as @jobseeker" do
      Jobseeker.stub(:find).with("37") { mock_jobseeker }
      get :show, :id => "37"
      assigns(:jobseeker).should be(mock_jobseeker)
    end
  end

  describe "GET new" do
    it "assigns a new jobseeker as @jobseeker" do
      Jobseeker.stub(:new) { mock_jobseeker }
      get :new
      assigns(:jobseeker).should be(mock_jobseeker)
    end
  end

  describe "GET edit" do
    it "assigns the requested jobseeker as @jobseeker" do
      Jobseeker.stub(:find).with("37") { mock_jobseeker }
      get :edit, :id => "37"
      assigns(:jobseeker).should be(mock_jobseeker)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created jobseeker as @jobseeker" do
        Jobseeker.stub(:new).with({'these' => 'params'}) { mock_jobseeker(:save => true) }
        post :create, :jobseeker => {'these' => 'params'}
        assigns(:jobseeker).should be(mock_jobseeker)
      end

      it "redirects to the created jobseeker" do
        Jobseeker.stub(:new) { mock_jobseeker(:save => true) }
        post :create, :jobseeker => {}
        response.should redirect_to(jobseeker_url(mock_jobseeker))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jobseeker as @jobseeker" do
        Jobseeker.stub(:new).with({'these' => 'params'}) { mock_jobseeker(:save => false) }
        post :create, :jobseeker => {'these' => 'params'}
        assigns(:jobseeker).should be(mock_jobseeker)
      end

      it "re-renders the 'new' template" do
        Jobseeker.stub(:new) { mock_jobseeker(:save => false) }
        post :create, :jobseeker => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jobseeker" do
        Jobseeker.stub(:find).with("37") { mock_jobseeker }
        mock_jobseeker.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :jobseeker => {'these' => 'params'}
      end

      it "assigns the requested jobseeker as @jobseeker" do
        Jobseeker.stub(:find) { mock_jobseeker(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:jobseeker).should be(mock_jobseeker)
      end

      it "redirects to the jobseeker" do
        Jobseeker.stub(:find) { mock_jobseeker(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(jobseeker_url(mock_jobseeker))
      end
    end

    describe "with invalid params" do
      it "assigns the jobseeker as @jobseeker" do
        Jobseeker.stub(:find) { mock_jobseeker(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:jobseeker).should be(mock_jobseeker)
      end

      it "re-renders the 'edit' template" do
        Jobseeker.stub(:find) { mock_jobseeker(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jobseeker" do
      Jobseeker.stub(:find).with("37") { mock_jobseeker }
      mock_jobseeker.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the jobseekers list" do
      Jobseeker.stub(:find) { mock_jobseeker }
      delete :destroy, :id => "1"
      response.should redirect_to(jobseekers_url)
    end
  end

end
