require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe UnemployedsController do

  def mock_unemployed(stubs={})
    @mock_unemployed ||= mock_model(Unemployed, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all unemployeds as @unemployeds" do
      Unemployed.stub(:all) { [mock_unemployed] }
      get :index
      assigns(:unemployeds).should eq([mock_unemployed])
    end
  end

  describe "GET show" do
    it "assigns the requested unemployed as @unemployed" do
      Unemployed.stub(:find).with("37") { mock_unemployed }
      get :show, :id => "37"
      assigns(:unemployed).should be(mock_unemployed)
    end
  end

  describe "GET new" do
    it "assigns a new unemployed as @unemployed" do
      Unemployed.stub(:new) { mock_unemployed }
      get :new
      assigns(:unemployed).should be(mock_unemployed)
    end
  end

  describe "GET edit" do
    it "assigns the requested unemployed as @unemployed" do
      Unemployed.stub(:find).with("37") { mock_unemployed }
      get :edit, :id => "37"
      assigns(:unemployed).should be(mock_unemployed)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created unemployed as @unemployed" do
        Unemployed.stub(:new).with({'these' => 'params'}) { mock_unemployed(:save => true) }
        post :create, :unemployed => {'these' => 'params'}
        assigns(:unemployed).should be(mock_unemployed)
      end

      it "redirects to the created unemployed" do
        Unemployed.stub(:new) { mock_unemployed(:save => true) }
        post :create, :unemployed => {}
        response.should redirect_to(unemployed_url(mock_unemployed))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved unemployed as @unemployed" do
        Unemployed.stub(:new).with({'these' => 'params'}) { mock_unemployed(:save => false) }
        post :create, :unemployed => {'these' => 'params'}
        assigns(:unemployed).should be(mock_unemployed)
      end

      it "re-renders the 'new' template" do
        Unemployed.stub(:new) { mock_unemployed(:save => false) }
        post :create, :unemployed => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested unemployed" do
        Unemployed.stub(:find).with("37") { mock_unemployed }
        mock_unemployed.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :unemployed => {'these' => 'params'}
      end

      it "assigns the requested unemployed as @unemployed" do
        Unemployed.stub(:find) { mock_unemployed(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:unemployed).should be(mock_unemployed)
      end

      it "redirects to the unemployed" do
        Unemployed.stub(:find) { mock_unemployed(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(unemployed_url(mock_unemployed))
      end
    end

    describe "with invalid params" do
      it "assigns the unemployed as @unemployed" do
        Unemployed.stub(:find) { mock_unemployed(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:unemployed).should be(mock_unemployed)
      end

      it "re-renders the 'edit' template" do
        Unemployed.stub(:find) { mock_unemployed(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested unemployed" do
      Unemployed.stub(:find).with("37") { mock_unemployed }
      mock_unemployed.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the unemployeds list" do
      Unemployed.stub(:find) { mock_unemployed }
      delete :destroy, :id => "1"
      response.should redirect_to(unemployeds_url)
    end
  end

end
